### PR TITLE
add Anna Krystalli to team

### PR DESCRIPTION
**Pull request by annakrystalli**

### CODE REVIEW

**Comment by annakrystalli** [comment]
Pinging @nickreich 😄

**Comment by nickreich** [comment]
I suggest cropping the photo so your face is right in the middle. otherwise, the circular cropping will cut out part of your face. We could also merge and build and see what it looks like? Otherwise, it looks good to me.

**Comment by annakrystalli** [comment]
Done!

**Comment by nickreich** [comment]
I still think it will look a little bit off-center (your face really needs to be in the middle of the frame!). But I'll merge and build and you can decide whether you want to adjust.

**Comment by annakrystalli** [comment]
Looks good built! Thanks for the invite to the team website :)

**Comment by nickreich** [comment]
Glad to have the collaboration made official now that it's on the website!

**Pull request merged**
