### PR TITLE
Added Trust Profile to Website

### PR DESCRIPTION
**Pull request by TrustChi**

### CODE REVIEW

**Comment by nickreich** [comment]
@TrustChi can you (a) zoom the photo in a bit, so your face will be more central in the picture? (b) make sure the image is fairly small in size. like it doesn't need to be above 300KB to be good enough quality for a small website head-shot.

**Comment by TrustChi** [comment]
@nickreich I resized the photo, and the file is less than 300KB now. Let me know if this is better.

**Comment by nickreich** [comment]
Let's see how it looks. I think it's possible that you'd want your face to be a bit more centered so the top of your head is cut off, but we can see how it looks. I'm always too picky/concerned about these small details anyways.

**Comment by nickreich** [comment]
I also made one minor change to the text about your date of graduation.

**Pull request merged**
